namespace Schedule1Recipes
{
    internal sealed class WeedStrainList(ComboBox ListDropdown, ComboBox PricesDropdown)
    {
        private ComboBox ListDropdown { get; set; } = ListDropdown;
        private ComboBox PricesDropdown { get; set; } = PricesDropdown;

        // List all weeds
        public void AddWeedList()
        {
            string[] items = [
                "Afghan Punch",
                "Afghan Queef",
                "Afghan Rhino",
                "Aspen Death",
                "Aspen Fruit",
                "Aspen Mint",
                "Aspen Rhino",
                "Aspen Smegma",
                "Banana Cheese",
                "Banana Diamond",
                "Banana Dick",
                "Banana Thunderfuck",
                "Big Crack",
                "Big Cum",
                "Big Express",
                "Big Fruit",
                "Bio Bud",
                "Bio Mint",
                "Bio Puke",
                "California Death",
                "California Gold",
                "California Grool",
                "California Puke",
                "California Punch",
                "California Rhino",
                "California Smegma",
                "Dark Bud",
                "Dark Ghost",
                "Death Cock",
                "Death Urkle",
                "Dream Cum",
                "Extreme Balls",
                "Extreme Durkle",
                "Extreme Mokey",
                "Fat Cum",
                "Fat Fuel",
                "Fat Mint",
                "Fat Shart",
                "Fruity Ass",
                "Fruity Balls",
                "Fruity Cum",
                "Fruity Haze",
                "Fruity Rhino",
                "Girl Scout Crystal",
                "Girl Scout Dick",
                "Girl Scout Punch",
                "Gorilla Splooge",
                "Gorilla Stink",
                "Granddaddy Cookies",
                "Granddaddy Stink",
                "Hairy Balls",
                "Hairy Gold",
                "Hairy Mint",
                "Hairy Shart",
                "Ice Cream Durkle",
                "Island Cock",
                "Island Rhino",
                "LA Crack",
                "Mega Bud",
                "Mega Cheese",
                "Mega Diesel",
                "Mega Fuel",
                "Mega Monkey",
                "Mega Punch",
                "Mega Rhino",
                "Miracle Crack",
                "Miracle McLovin",
                "Miracle Shart",
                "Nightmare Balls",
                "Nightmare Crystal",
                "Nightmare Grool",
                "Nightmare Monkey",
                "OG Rhino",
                "OG Splooge",
                "Pink Ass",
                "Pink Balls",
                "Pink Fruit",
                "Pink Fuel",
                "Pink Haze",
                "Pink Piss",
                "Pink Rhino",
                "Shiny Shart",
                "Shiny Splooge",
                "Slimy Balls",
                "Slimy Haze",
                "Slimy Splooge",
                "Stinky Cake",
                "Stinky Puke",
                "Stinky Rhino",
                "Strawberry Cheese",
                "Strawberry Durkle",
                "Strawberry Mint",
                "Strawberry Piss",
                "Strawberry Shart",
                "Strawberry Thunderfuck",
                "Super Dick",
                "Super Slime",
                "Purple Punch",
                "Sweet Assblaster",
                "Sweet Cheese",
                "Sweet Cum",
                "Sweet Fruit",
                "Sweet Haze",
                "Sweet Shart",
                "Sweet Thunderfuck",
                "Thick Balls",
                "Thick Cock",
                "Thick Dick",
                "Thick McLovin",
                "Thick Piss",
                "Thick Stink",
                "Tokyo Ass",
                "Tokyo Balls",
                "Tokyo Mint",
                "Tokyo Piss",
                "Ultra Cake",
                "Ultra Cookies",
                "Ultra Grool",
                "Ultra Puke",
                "Wedding Ass",
                "Wedding Bud",
                "Wedding Express",
                "Wedding Puke",
                "Wedding Rhino",
                "Wedding Thunderfuck",
                "White Cheese",
                "White Slime",
                "White Smegma",
                "White Stink"
            ];
            ListDropdown.Items.Clear(); // Clear the old list
            Array.Sort(items);
            foreach (string item in items)
            {
                ListDropdown.Items.Add(item);
            }
            ListDropdown.SelectedIndex = 0;
        }
    }
}
